### ISSUE TITLE
problem pushing to git hub

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/swift-arrays-lab#2]
hi, I wanted to git push my changes and i get this error message: 
katarzynas-MacBook-Pro:swift-arrays-lab-swift-intro-000 kasiarosenberg$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
katarzynas-MacBook-Pro:swift-arrays-lab-swift-intro-000 kasiarosenberg$ git add .
katarzynas-MacBook-Pro:swift-arrays-lab-swift-intro-000 kasiarosenberg$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
katarzynas-MacBook-Pro:swift-arrays-lab-swift-intro-000 kasiarosenberg$ git commit -m "bla"
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
katarzynas-MacBook-Pro:swift-arrays-lab-swift-intro-000 kasiarosenberg$ git push
Username for 'https://github.com': kasiarosenb
Password for 'https://kasiarosenb@github.com': 
remote: Permission to learn-co-students/swift-arrays-lab-swift-intro-000.git denied to kasiarosenb.
fatal: unable to access 'https://github.com/learn-co-students/swift-arrays-lab-swift-intro-000.git/': The requested URL returned error: 403
katarzynas-MacBook-Pro:swift-arrays-lab-swift-intro-000 kasiarosenberg$

**Comment by JimCampagno** [comment]
Hey @kasiarosenb 

You should first write `git add .` which will stage the un-staged files. Then you should write `git commit -m "WRITE_MESSAGE_HERE"` creating a message that pertains to the changes you are now committing. After performing those two commands you should then write `git push` to push up these changes to GitHub.

Let me know if this solves your problem. If not, feel free to open up another issue on this lab.
