### ISSUE TITLE
Typos in Questions 5 and 9

### ISSUE THREAD

**Issue by ryans-git** [learn-co-curriculum/swift-arrays-lab#3]
5) Create a second array called 'dessertList' with a type specified **using** and contains the string values "Cookie dough", "Icecream"
-wording is off, can just delete **using** to fix I think?

9) Create a function named 'lifesEssential' that **accepts a string of arrays as a parameter** called 'ingredients' and returns a boolean...
-Should be an "array of strings"

**Comment by JimCampagno** [comment]
@ryan1twice 

Thanks. All fixed.
